// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(opaque_ke_uniffiFFI)
import opaque_ke_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_opaque_ke_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_opaque_ke_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOpaqueKeUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct ClientLoginFinishResult: Equatable, Hashable {
    public var credentialFinalization: Data
    public var sessionKey: Data
    public var exportKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(credentialFinalization: Data, sessionKey: Data, exportKey: Data) {
        self.credentialFinalization = credentialFinalization
        self.sessionKey = sessionKey
        self.exportKey = exportKey
    }

    

    
}

#if compiler(>=6)
extension ClientLoginFinishResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientLoginFinishResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientLoginFinishResult {
        return
            try ClientLoginFinishResult(
                credentialFinalization: FfiConverterData.read(from: &buf), 
                sessionKey: FfiConverterData.read(from: &buf), 
                exportKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClientLoginFinishResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.credentialFinalization, into: &buf)
        FfiConverterData.write(value.sessionKey, into: &buf)
        FfiConverterData.write(value.exportKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientLoginFinishResult_lift(_ buf: RustBuffer) throws -> ClientLoginFinishResult {
    return try FfiConverterTypeClientLoginFinishResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientLoginFinishResult_lower(_ value: ClientLoginFinishResult) -> RustBuffer {
    return FfiConverterTypeClientLoginFinishResult.lower(value)
}


public struct ClientLoginStartResult: Equatable, Hashable {
    public var credentialRequest: Data
    public var clientRegistration: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(credentialRequest: Data, clientRegistration: Data) {
        self.credentialRequest = credentialRequest
        self.clientRegistration = clientRegistration
    }

    

    
}

#if compiler(>=6)
extension ClientLoginStartResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientLoginStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientLoginStartResult {
        return
            try ClientLoginStartResult(
                credentialRequest: FfiConverterData.read(from: &buf), 
                clientRegistration: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClientLoginStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.credentialRequest, into: &buf)
        FfiConverterData.write(value.clientRegistration, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientLoginStartResult_lift(_ buf: RustBuffer) throws -> ClientLoginStartResult {
    return try FfiConverterTypeClientLoginStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientLoginStartResult_lower(_ value: ClientLoginStartResult) -> RustBuffer {
    return FfiConverterTypeClientLoginStartResult.lower(value)
}


public struct ClientRegistrationFinishResult: Equatable, Hashable {
    public var registrationUpload: Data
    public var exportKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(registrationUpload: Data, exportKey: Data) {
        self.registrationUpload = registrationUpload
        self.exportKey = exportKey
    }

    

    
}

#if compiler(>=6)
extension ClientRegistrationFinishResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientRegistrationFinishResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientRegistrationFinishResult {
        return
            try ClientRegistrationFinishResult(
                registrationUpload: FfiConverterData.read(from: &buf), 
                exportKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClientRegistrationFinishResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.registrationUpload, into: &buf)
        FfiConverterData.write(value.exportKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientRegistrationFinishResult_lift(_ buf: RustBuffer) throws -> ClientRegistrationFinishResult {
    return try FfiConverterTypeClientRegistrationFinishResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientRegistrationFinishResult_lower(_ value: ClientRegistrationFinishResult) -> RustBuffer {
    return FfiConverterTypeClientRegistrationFinishResult.lower(value)
}


public struct ClientRegistrationStartResult: Equatable, Hashable {
    public var registrationRequest: Data
    public var clientRegistration: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(registrationRequest: Data, clientRegistration: Data) {
        self.registrationRequest = registrationRequest
        self.clientRegistration = clientRegistration
    }

    

    
}

#if compiler(>=6)
extension ClientRegistrationStartResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeClientRegistrationStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ClientRegistrationStartResult {
        return
            try ClientRegistrationStartResult(
                registrationRequest: FfiConverterData.read(from: &buf), 
                clientRegistration: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ClientRegistrationStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.registrationRequest, into: &buf)
        FfiConverterData.write(value.clientRegistration, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientRegistrationStartResult_lift(_ buf: RustBuffer) throws -> ClientRegistrationStartResult {
    return try FfiConverterTypeClientRegistrationStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeClientRegistrationStartResult_lower(_ value: ClientRegistrationStartResult) -> RustBuffer {
    return FfiConverterTypeClientRegistrationStartResult.lower(value)
}


public struct ServerLoginStartResult: Equatable, Hashable {
    public var credentialResponse: Data
    public var serverLogin: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(credentialResponse: Data, serverLogin: Data) {
        self.credentialResponse = credentialResponse
        self.serverLogin = serverLogin
    }

    

    
}

#if compiler(>=6)
extension ServerLoginStartResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeServerLoginStartResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ServerLoginStartResult {
        return
            try ServerLoginStartResult(
                credentialResponse: FfiConverterData.read(from: &buf), 
                serverLogin: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: ServerLoginStartResult, into buf: inout [UInt8]) {
        FfiConverterData.write(value.credentialResponse, into: &buf)
        FfiConverterData.write(value.serverLogin, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServerLoginStartResult_lift(_ buf: RustBuffer) throws -> ServerLoginStartResult {
    return try FfiConverterTypeServerLoginStartResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeServerLoginStartResult_lower(_ value: ServerLoginStartResult) -> RustBuffer {
    return FfiConverterTypeServerLoginStartResult.lower(value)
}


public enum Hash2CurveError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case InternalError(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Hash2CurveError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHash2CurveError: FfiConverterRustBuffer {
    typealias SwiftType = Hash2CurveError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Hash2CurveError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .InternalError(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Hash2CurveError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .InternalError(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHash2CurveError_lift(_ buf: RustBuffer) throws -> Hash2CurveError {
    return try FfiConverterTypeHash2CurveError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHash2CurveError_lower(_ value: Hash2CurveError) -> RustBuffer {
    return FfiConverterTypeHash2CurveError.lower(value)
}


public enum LoginError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Generic(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension LoginError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLoginError: FfiConverterRustBuffer {
    typealias SwiftType = LoginError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LoginError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LoginError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginError_lift(_ buf: RustBuffer) throws -> LoginError {
    return try FfiConverterTypeLoginError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLoginError_lower(_ value: LoginError) -> RustBuffer {
    return FfiConverterTypeLoginError.lower(value)
}


public enum RegistrationError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Generic(String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension RegistrationError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRegistrationError: FfiConverterRustBuffer {
    typealias SwiftType = RegistrationError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RegistrationError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Generic(
            try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RegistrationError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Generic(v1):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationError_lift(_ buf: RustBuffer) throws -> RegistrationError {
    return try FfiConverterTypeRegistrationError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRegistrationError_lower(_ value: RegistrationError) -> RustBuffer {
    return FfiConverterTypeRegistrationError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
/**
 * Completes the OPAQUE login flow and derives the session key on the client side.
 *
 * # Parameters
 * - `credential_response`: The server's credential response message.
 * - `client_registration`: The client's internal login state from `client_login_start`.
 * - `password`: The user's password.
 * - `context`: Application-specific context for the session.
 * - `client_identifier`: The client's identity.
 * - `server_identifier`: The server's identity.
 */
public func clientLoginFinish(credentialResponse: Data, clientRegistration: Data, password: Data, context: Data, clientIdentifier: Data, serverIdentifier: Data)throws  -> ClientLoginFinishResult  {
    return try  FfiConverterTypeClientLoginFinishResult_lift(try rustCallWithError(FfiConverterTypeLoginError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_client_login_finish(
        FfiConverterData.lower(credentialResponse),
        FfiConverterData.lower(clientRegistration),
        FfiConverterData.lower(password),
        FfiConverterData.lower(context),
        FfiConverterData.lower(clientIdentifier),
        FfiConverterData.lower(serverIdentifier),$0
    )
})
}
/**
 * Initiates the OPAQUE login flow on the client side.
 *
 * This function takes the user's password and returns the initial credential request
 * to be sent to the server, as well as the client's internal login state.
 */
public func clientLoginStart(password: Data)throws  -> ClientLoginStartResult  {
    return try  FfiConverterTypeClientLoginStartResult_lift(try rustCallWithError(FfiConverterTypeLoginError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_client_login_start(
        FfiConverterData.lower(password),$0
    )
})
}
/**
 * Completes the OPAQUE registration flow on the client side.
 *
 * This function takes the user's password, the client's registration state,
 * the server's registration response, and optional client and server identifiers.
 * It returns a RegistrationUpload to be sent to the server and the export key.
 */
public func clientRegistrationFinish(password: Data, clientRegistration: Data, registrationResponse: Data, clientIdentifier: Data?, serverIdentifier: Data?)throws  -> ClientRegistrationFinishResult  {
    return try  FfiConverterTypeClientRegistrationFinishResult_lift(try rustCallWithError(FfiConverterTypeRegistrationError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_client_registration_finish(
        FfiConverterData.lower(password),
        FfiConverterData.lower(clientRegistration),
        FfiConverterData.lower(registrationResponse),
        FfiConverterOptionData.lower(clientIdentifier),
        FfiConverterOptionData.lower(serverIdentifier),$0
    )
})
}
/**
 * Initiates the OPAQUE registration flow on the client side.
 *
 * This function takes the user's password and returns the initial registration message to be sent to the server,
 * and the client's internal registration state.
 */
public func clientRegistrationStart(password: Data)throws  -> ClientRegistrationStartResult  {
    return try  FfiConverterTypeClientRegistrationStartResult_lift(try rustCallWithError(FfiConverterTypeRegistrationError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_client_registration_start(
        FfiConverterData.lower(password),$0
    )
})
}
/**
 * Hashes input data to a curve point using the hash_to_curve algorithm from RFC 9380.
 *
 * This function implements the hash-to-curve operation as specified in RFC 9380,
 * using the NIST P-256 curve and SHA-256 hash function.
 *
 * # Arguments
 * * `input` - The input data to hash
 * * `dst` - Domain separation tag
 *
 * # Returns
 * The serialized compressed curve point as a 33-byte array (compressed SEC1 format)
 */
public func hashToCurveP256Sha256(input: Data, dst: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeHash2CurveError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_hash_to_curve_p256_sha256(
        FfiConverterData.lower(input),
        FfiConverterData.lower(dst),$0
    )
})
}
/**
 * Hashes input data to a curve point using the hash_to_curve algorithm from RFC 9380.
 *
 * This function implements the hash-to-curve operation as specified in RFC 9380,
 * using the Ristretto255 group and SHA-512 hash function.
 *
 * # Arguments
 * * `input` - The input data to hash
 * * `dst` - Domain separation tag
 *
 * # Returns
 * The serialized compressed curve point as a 32-byte array
 */
public func hashToCurveRistretto255Sha512(input: Data, dst: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeHash2CurveError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_hash_to_curve_ristretto255_sha512(
        FfiConverterData.lower(input),
        FfiConverterData.lower(dst),$0
    )
})
}
public func serverSetup() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_opaque_ke_uniffi_fn_func_server_setup($0
    )
})
}
/**
 * Completes the OPAQUE login flow on the server side.
 *
 * This function takes the server's login state from the start step,
 * the client's credential finalization message,
 * and optional parameters for context and identifiers.
 * It returns the session key on successful authentication.
 */
public func serverLoginFinish(serverLogin: Data, credentialFinalization: Data, context: Data?, clientIdentifier: Data?, serverIdentifier: Data?)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeLoginError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_server_login_finish(
        FfiConverterData.lower(serverLogin),
        FfiConverterData.lower(credentialFinalization),
        FfiConverterOptionData.lower(context),
        FfiConverterOptionData.lower(clientIdentifier),
        FfiConverterOptionData.lower(serverIdentifier),$0
    )
})
}
/**
 * The first step of the OPAQUE login flow on the server side.
 *
 * This function takes a previously generated server setup,
 * the user's password file (from registration),
 * a credential request from the client,
 * a credential identifier to look up the user,
 * and optional parameters for context and identifiers.
 * It returns a credential response to be sent to the client,
 * and a server login state to be used in the finish step.
 */
public func serverLoginStart(serverSetup: Data, passwordFile: Data, credentialRequest: Data, credentialIdentifier: Data, context: Data?, clientIdentifier: Data?, serverIdentifier: Data?)throws  -> ServerLoginStartResult  {
    return try  FfiConverterTypeServerLoginStartResult_lift(try rustCallWithError(FfiConverterTypeLoginError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_server_login_start(
        FfiConverterData.lower(serverSetup),
        FfiConverterData.lower(passwordFile),
        FfiConverterData.lower(credentialRequest),
        FfiConverterData.lower(credentialIdentifier),
        FfiConverterOptionData.lower(context),
        FfiConverterOptionData.lower(clientIdentifier),
        FfiConverterOptionData.lower(serverIdentifier),$0
    )
})
}
/**
 * Completes the QPAQUE login flow on the server side.
 *
 * Takes a RegistrationUpload from the client and returns a password file to be stored server side
 */
public func serverRegistrationFinish(registrationUpload: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeRegistrationError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_server_registration_finish(
        FfiConverterData.lower(registrationUpload),$0
    )
})
}
/**
 * The first sep of the OPAQUE login flow on the server side.
 *
 * This function takes a previously generated server setup,
 * a RegistrationRequest generated by the client,
 * and the client's ID.
 * It returns a RegistrationResponse to be returned to the client.
 */
public func serverRegistrationStart(serverSetup: Data, registrationRequest: Data, clientId: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeRegistrationError_lift) {
    uniffi_opaque_ke_uniffi_fn_func_server_registration_start(
        FfiConverterData.lower(serverSetup),
        FfiConverterData.lower(registrationRequest),
        FfiConverterData.lower(clientId),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_opaque_ke_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_client_login_finish() != 10030) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_client_login_start() != 4310) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_client_registration_finish() != 21469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_client_registration_start() != 55213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_hash_to_curve_p256_sha256() != 44535) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_hash_to_curve_ristretto255_sha512() != 49397) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_server_setup() != 53710) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_server_login_finish() != 45094) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_server_login_start() != 28024) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_server_registration_finish() != 53317) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_opaque_ke_uniffi_checksum_func_server_registration_start() != 8822) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOpaqueKeUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all